[package]
name = "sieve"
version = "0.1.0"
authors = ["Sereinity <sereinity@sereinity.fr>"]
edition = "2018"

[dependencies]
clap = {version = "4.3", features = ["derive"]}
slog = {version = "2.7", features = ["max_level_trace"]}
slog-async = "2.7"
slog-term = "2.9"
