[package]
name = "sieve"
version = "0.1.0"
authors = ["Benoît Marcelin <sereinity@sereinity.fr>"]

[dependencies]
clap = "^2"
slog = {version = "^2", features = ["max_level_trace"]}
slog-async = "^2"
slog-term = "^2"
